GET http://localhost:5000/api/users/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZiMWY1Y2E0Mzg5ODhlYjdiMWU2NjkiLCJlbWFpbCI6ImphbmVuZG9lQGdtYWlsLmNvbSIsImlhdCI6MTcxODY0MzgyNCwiZXhwIjoxNzE4NjQ3NDI0fQ.Ctkn8ToArlYH-EnFYcgRLwi0Uj-VZ6_R4lQCF5QMoUU HTTP/1.1