GET http://localhost:5000/api/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZiMWY1Y2E0Mzg5ODhlYjdiMWU2NjkiLCJlbWFpbCI6ImphbmVuZG9lQGdtYWlsLmNvbSIsImlhdCI6MTcxODcyNTQ2NSwiZXhwIjoxNzE4NzI5MDY1fQ.ENjPynPgEyLdqSzJ2sGpcL_USPsU5UgPdWlG76W-Mxs