DELETE http://localhost:5000/api/tasks/666c67332a21363545e01785 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZiMWY1Y2E0Mzg5ODhlYjdiMWU2NjkiLCJlbWFpbCI6ImphbmVuZG9lQGdtYWlsLmNvbSIsImlhdCI6MTcxODk4NjE4OSwiZXhwIjoxNzE4OTg2MjQ5fQ.DjMpOwICd5Vl3g0-SaIa6XZX80CM559oPRFvl51d1AU